name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3
        ndk: 21.4.7075529

    # Grant execute permission to Gradlew
    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    # Build APK
    - name: Build the APK
      run: ./gradlew assembleRelease --stacktrace

    # List the output directory to verify APK location
    - name: List build outputs
      run: ls -R app/build/outputs

    # Upload APK as artifact (adjust path if necessary)
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
